EAPOL_REPLAY_COUNTER_LENGTH = 8
EAPOL_NONCE_LENGTH = 32
EAPOL_KEY_IV_LENGTH = 16
EAPOL_KEY_RSC_LENGTH = 8
EAPOL_KEY_ID_LENGTH = 8
EAPOL_MIC_LENGTH = 16
EAPOL_KEY_DATA_LENGTH_FIELD = 2
EAPOL_PMKID_LENGTH = 16
